// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const stickersContainer: string;
export const primaryStickersContainer: string;
export const mainLogoContainer: string;
export const logoRoot: string;
export const logo: string;
export const logoAndInstagramContainer: string;
export const secondaryStickersContainer: string;
export const newsletterContainer: string;
export const spotifyContainer: string;
export const mobileTopLinks: string;
export const mobileLogoContainer: string;
export const mobileSpotifyContainer: string;
export const mobileInstagramContainer: string;
