// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const topBadges: string;
export const bottomBadges: string;
export const gifRoot: string;
export const gif: string;
